### PR TITLE
Add CLI for testing from npm scripts

### PR DESCRIPTION
**Pull request by paulmelnikow**
For #12

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Ping @rowanmanning, any thoughts?

**Comment by rowanmanning** [comment]
Hi Paul, I haven't had chance to look at this yet. I should be able to review later in the week

**Comment by paulmelnikow** [comment]
Okay, thanks.

**Comment by paulmelnikow** [comment]
Any thoughts? There's not much here. If it's not something you want to include, nbd, I can publish a separate package. @rowanmanning

**Comment by jbach** [comment]
Any updates on this?
@paulmelnikow: I think, you should add `minimist` to `dependencies`.

**Comment by paulmelnikow** [comment]
I went ahead and published this myself: https://www.npmjs.com/package/hasbin-cli

**Pull request closed without merging**
