### PR TITLE
Split path using the platform specific path delimiter

### PR DESCRIPTION
**Pull request by moddular**
Should hopefully resolve issue #1

### CODE REVIEW

**Comment by rowanmanning** [comment]
Thanks @moddular :) I'll take a look on Monday on a Windows VM (I don't have one set up at home) unless you can verify that it's fixed?

**Comment by moddular** [comment]
Hmm, it fixes the issue of being able to search the path on windows, it doesn't fix the issue that windows binaries might have file extensions :( e.g. node.exe not node. The supported extensions seem to be available in process.env.PATHEXT - I'll see if I can update the patch tomorrow to take this into account.

**Comment by moddular** [comment]
So with a PATH

`C:\Program Files\nodejs;C:\Users\IEUser\App Data\Roaming\npm`

and a PATHEXT

`.CMD;.EXE`

then:

`hasbin.all(['node', 'npm'], function() { });`

would check:
- `C:\Program Files\nodejs\node.EXE`
- `C:\Program Files\nodejs\node.CMD`
- `C:\Users\IEUser\App Data\Roaming\npm\node.EXE`
- `C:\Users\IEUser\App Data\Roaming\npm\node.CMD`
- `C:\Program Files\nodejs\npm.EXE`
- `C:\Program Files\nodejs\npm.CMD`
- `C:\Users\IEUser\App Data\Roaming\npm\npm.EXE`
- `C:\Users\IEUser\App Data\Roaming\npm\npm.CMD`

if PATHEXT is not set it would just check the name of the binary in each location in the PATH. (Tested on windows 8.1)

**Comment by rowanmanning** [comment]
Looks great! Thanks, Andrew :)

**Pull request merged**
